---
- name: win_file module demo
  hosts: all
  become: false
  tasks:
    - name: Insert settings NRPE
      blockinfile:
        path: c:\Program Files\NSClient++\nsclient.ini
        insertafter: '[/settings/NRPE/server]'
        block: |
          '; # DH KEY'
          'dh = ${certificate-path}/nrpe_dh_2048.pem'
          
