---
- name: copy pem
  hosts: all
  become: yes
  become_method: runas
  become_user: Administrator
  tasks:
    - name: Copy a single file
      copy:
        src: /tmp/b4.pem
        dest: C:\Temp\renamed-foo.conf
#        remote_src: yes
