---
- name: copy pem
  hosts: all
  become: false
  gather_facts: false  
  vars:
    source: /tmp/b4.pem
    destination: C:\Temp\renamed-foo1.conf
  tasks:
    - name: Copy a single file
      win_copy:
        src: "{{ source }}"
        dest: "{{ destination }}"
#        remote_src: yes
