---
- name: win_file module demo
  hosts: all
  become: false
  vars:
    mydir: 'C:\Tmp\dupa'
  tasks:
    - name: Create a directory 
      win_file:
        path: "{{  mydir  }}"
        state: directory
