---
- hosts: all
  gather_facts: no
  tasks:
  - name: Add some hosts entries
    blockinfile:
      path: C:\Windows\System32\drivers\etc\hosts
      block: |
        127.0.0.1 foobar
        192.168.1.10 barfoo
